import assert from 'node:assert/strict';
import { mkdir, mkdtemp, readFile, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import test from 'node:test';
import { auditWorkspace, refreshWorkspaceMemory, walkAgentsChain } from '../lib/workspace-audit.mjs';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');

async function writeMinimalWorkspace(root) {
  await mkdir(path.join(root, 'cocoder', 'memory'), { recursive: true });
  await mkdir(path.join(root, 'cocoder', 'standards'), { recursive: true });
  await writeFile(
    path.join(root, 'cocoder', 'AGENTS.md'),
    [
      '# Workspace',
      '',
      'See [`standards/AGENTS.md`](./standards/AGENTS.md) for standards routing.',
      ''
    ].join('\n'),
    'utf8'
  );
  await writeFile(path.join(root, 'cocoder', 'standards', 'AGENTS.md'), '# Standards\n', 'utf8');
}

test('walkAgentsChain follows AGENTS.md links from cocoder/AGENTS.md', async () => {
  const tmp = await mkdtemp(path.join(os.tmpdir(), 'cocoder-audit-chain-'));
  try {
    await writeMinimalWorkspace(tmp);
    const result = await walkAgentsChain({ workspaceRoot: tmp });
    assert.equal(result.ok, true);
    assert.equal(result.chain.length, 2);
    assert.match(result.chain[1].repoRelative, /cocoder\/standards\/AGENTS\.md$/);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
});

test('audit-workspace writes onboarding-questions.md stub', async () => {
  const tmp = await mkdtemp(path.join(os.tmpdir(), 'cocoder-audit-write-'));
  try {
    await writeMinimalWorkspace(tmp);
    const result = await auditWorkspace({ workspaceRoot: tmp, now: '2026-05-23T12:00:00.000Z' });
    assert.equal(result.ok, true);
    const body = await readFile(result.outputPath, 'utf8');
    assert.match(body, /Generated by `cocoder audit-workspace`/);
    assert.match(body, /cocoder\/AGENTS\.md/);
    assert.match(body, /Open questions/);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
});

test('refresh-memory updates codebase-map.md from audit results', async () => {
  const tmp = await mkdtemp(path.join(os.tmpdir(), 'cocoder-refresh-memory-'));
  try {
    await writeMinimalWorkspace(tmp);
    await mkdir(path.join(tmp, 'src'), { recursive: true });
    const result = await refreshWorkspaceMemory({ workspaceRoot: tmp, now: '2026-05-23T12:00:00.000Z' });
    assert.equal(result.ok, true);
    const body = await readFile(result.outputPath, 'utf8');
    assert.match(body, /Generated by `cocoder refresh-memory`|Updated by `cocoder refresh-memory`/);
    assert.match(body, /`src\/`/);
    assert.match(body, /AGENTS\.md chain/);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
});

test('audit-workspace fails closed when cocoder/AGENTS.md is missing', async () => {
  const tmp = await mkdtemp(path.join(os.tmpdir(), 'cocoder-audit-missing-'));
  try {
    await assert.rejects(() => auditWorkspace({ workspaceRoot: tmp }), /missing workspace entrypoint/);
  } finally {
    await rm(tmp, { recursive: true, force: true });
  }
});

test('dogfood workspace AGENTS chain includes memory and standards entrypoints', async () => {
  const result = await walkAgentsChain({ workspaceRoot: repoRoot });
  assert.equal(result.ok, true);
  const relatives = result.chain.map((item) => item.repoRelative);
  assert.ok(relatives.includes('cocoder/AGENTS.md'));
  assert.ok(relatives.includes('cocoder/memory/AGENTS.md'));
  assert.ok(relatives.includes('cocoder/standards/AGENTS.md'));
});
