import { mkdir, readdir, readFile, stat, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { pathExists } from './fs-utils.mjs';

const AGENTS_LINK_PATTERN = /\[[^\]]*]\(([^)]+)\)/g;

export async function walkAgentsChain({ workspaceRoot, maxDepth = 12 } = {}) {
  if (!workspaceRoot) throw new Error('walkAgentsChain requires workspaceRoot');
  const root = path.resolve(workspaceRoot);
  const cocoderRoot = path.join(root, 'cocoder');
  const entry = path.join(cocoderRoot, 'AGENTS.md');
  if (!(await pathExists(entry))) {
    throw new Error(`missing workspace entrypoint ${entry}`);
  }

  const visited = new Set();
  const chain = [];
  const missing = [];
  const queue = [{ filePath: entry, depth: 0 }];

  while (queue.length > 0) {
    const current = queue.shift();
    const normalized = path.normalize(current.filePath);
    if (visited.has(normalized)) continue;
    visited.add(normalized);

    if (!(await pathExists(normalized))) {
      missing.push({ from: current.from || null, target: normalized, reason: 'missing-file' });
      continue;
    }

    const content = await readFile(normalized, 'utf8');
    chain.push({
      filePath: normalized,
      repoRelative: path.relative(root, normalized).split(path.sep).join('/'),
      depth: current.depth
    });

    if (current.depth >= maxDepth) continue;

    for (const link of extractAgentsLinks(content, path.dirname(normalized), root)) {
      if (!link.endsWith('AGENTS.md')) continue;
      queue.push({ filePath: link, depth: current.depth + 1, from: normalized });
    }
  }

  return { ok: missing.length === 0, root, chain, missing };
}

export async function auditWorkspace({ workspaceRoot, now = new Date().toISOString() } = {}) {
  const walk = await walkAgentsChain({ workspaceRoot });
  const cocoderRoot = path.join(path.resolve(workspaceRoot), 'cocoder');
  const memoryDir = path.join(cocoderRoot, 'memory');
  const outputPath = path.join(memoryDir, 'onboarding-questions.md');

  const questions = buildOnboardingQuestions({ walk, now });
  await mkdir(memoryDir, { recursive: true });
  await writeFile(outputPath, questions, 'utf8');

  return {
    ok: walk.ok,
    workspaceRoot: path.resolve(workspaceRoot),
    chain: walk.chain.map((item) => item.repoRelative),
    missing: walk.missing,
    outputPath,
    stub: true,
    note: 'Full stack detection deferred to v0.2; AGENTS.md chain walk only.'
  };
}

export async function refreshWorkspaceMemory({ workspaceRoot, now = new Date().toISOString() } = {}) {
  const audit = await auditWorkspace({ workspaceRoot, now });
  const root = path.resolve(workspaceRoot);
  const layout = await summarizeWorkspaceLayout(root);
  const outputPath = path.join(root, 'cocoder', 'memory', 'codebase-map.md');
  const body = buildCodebaseMap({ audit, layout, now });
  await writeFile(outputPath, body, 'utf8');

  return {
    ok: audit.ok,
    workspaceRoot: root,
    audit,
    outputPath,
    stub: true,
    note: 'LLM-assisted refinement deferred to v0.2; directory listing + AGENTS chain only.'
  };
}

function extractAgentsLinks(content, baseDir, workspaceRoot) {
  const links = [];
  for (const match of content.matchAll(AGENTS_LINK_PATTERN)) {
    const raw = match[1].trim();
    if (!raw || URL_PATTERN.test(raw) || raw.startsWith('#')) continue;
    const withoutHash = raw.split('#')[0];
    if (!withoutHash.endsWith('.md')) continue;
    const resolved = path.resolve(baseDir, withoutHash);
    if (!resolved.startsWith(workspaceRoot)) continue;
    links.push(resolved);
  }
  return links;
}

const URL_PATTERN = /^(?:https?:|mailto:)/i;

function buildOnboardingQuestions({ walk, now }) {
  const lines = [
    '# Onboarding Questions',
    '',
    `Generated by \`cocoder audit-workspace\` at ${now}.`,
    '',
    'Full stack detection is deferred to v0.2. This stub records the AGENTS.md chain and surfaces broken links.',
    '',
    '## AGENTS.md chain',
    ''
  ];

  for (const item of walk.chain) {
    lines.push(`- [x] \`${item.repoRelative}\``);
  }

  lines.push('', '## Broken links', '');
  if (walk.missing.length === 0) {
    lines.push('- None detected in the AGENTS.md chain walk.');
  } else {
    for (const miss of walk.missing) {
      const from = miss.from ? path.basename(miss.from) : 'entry';
      lines.push(`- [ ] Missing target from \`${from}\`: \`${path.basename(miss.target)}\``);
    }
  }

  lines.push(
    '',
    '## Open questions (fill in as you learn the repo)',
    '',
    '- What is the primary application entrypoint (web, CLI, library)?',
    '- Which test command should personas run by default?',
    '- Where do architecture decisions live besides `cocoder/decisions/`?',
    '- Which persona routes are active for the current priority?',
    ''
  );

  return lines.join('\n');
}

async function summarizeWorkspaceLayout(workspaceRoot) {
  const entries = await readdir(workspaceRoot, { withFileTypes: true });
  const topLevel = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.name.startsWith('.')) continue;
    const full = path.join(workspaceRoot, entry.name);
    if (entry.isDirectory()) {
      const childCount = (await readdir(full)).length;
      topLevel.push({ name: entry.name, kind: 'directory', childCount });
    } else if (entry.isFile()) {
      const info = await stat(full);
      topLevel.push({ name: entry.name, kind: 'file', bytes: info.size });
    }
  }

  const cocoderDir = path.join(workspaceRoot, 'cocoder');
  const cocoderEntries = (await pathExists(cocoderDir))
    ? (await readdir(cocoderDir, { withFileTypes: true }))
        .filter((entry) => !entry.name.startsWith('.'))
        .map((entry) => entry.name)
        .sort()
    : [];

  return { topLevel, cocoderEntries };
}

function buildCodebaseMap({ audit, layout, now }) {
  const lines = [
    '# Codebase Map',
    '',
    `Updated by \`cocoder refresh-memory\` at ${now}.`,
    '',
    'This stub lists top-level layout and the AGENTS.md chain. LLM-assisted refinement is deferred to v0.2.',
    '',
    '## Workspace root',
    ''
  ];

  for (const entry of layout.topLevel) {
    if (entry.kind === 'directory') {
      lines.push(`- \`${entry.name}/\` (${entry.childCount} entries)`);
    } else {
      lines.push(`- \`${entry.name}\` (${entry.bytes} bytes)`);
    }
  }

  lines.push('', '## `cocoder/` directories and files', '');
  if (layout.cocoderEntries.length === 0) {
    lines.push('- `(missing cocoder/ directory)`');
  } else {
    for (const name of layout.cocoderEntries) {
      lines.push(`- \`cocoder/${name}\``);
    }
  }

  lines.push('', '## AGENTS.md chain', '');
  for (const item of audit.chain) {
    lines.push(`- \`${item}\``);
  }
  lines.push('');

  return lines.join('\n');
}
