// @cocoder/core — the I/O-agnostic heart of CoCoder v2 (ADR-0004/0008).
// Depends on nothing in the workspace; everything inward points here.
//
// As Phase 1 builds out, this barrel re-exports the real modules:
//   - data-model schema + RunStore port (Step 3)
//   - SessionHost port (Step 2)
//   - Adapter interface + preflight (Step 4)
//   - persona/play/priority loader (Step 4)
//   - write-scope + commit-gate (Step 5)
//   - the runner / launch composition (Step 6)

export const CORE_VERSION = '0.0.0'

export type {
  SessionRef,
  SpawnOptions,
  SessionStatus,
  SessionExited,
  SessionHost,
} from './session-host/index.js'

export type {
  RunStore,
  Workspace,
  Run,
  RunStatus,
  Session,
  WorkItem,
  WorkItemStatus,
  CommitLink,
  RunEvent,
} from './store/index.js'
export {
  openRunStore,
  migrateWorkspacePortableHistory,
  DEFAULT_PORTABLE_COUNTERS,
  coCoderRunReference,
  ensurePortableWorkspace,
  portableWorkspacePaths,
  readPortableRunById,
  recordPortableRunCreation,
  runDisplayName,
  runDisplayNumber,
  writePortableCounters,
  writePortableRun,
  type MigrateWorkspacePortableHistoryResult,
  type OpenRunStoreOptions,
  type RecordPortableRunCreationInput,
  type RunDisplayInput,
  SCHEMA_SQL,
} from './store/index.js'

export { probeDaemon, DEFAULT_OZ_PORT, type ProbeResult, type ProbeOptions } from './liveness/index.js'

export type {
  Persona,
  PersonaDelta,
  PersonaAssignment,
  PersonaRunMode,
  PlayAssignment,
  Assignments,
  ResolvedPersona,
  PersonaSources,
} from './personas/index.js'
export {
  parseFrontmatter,
  type Frontmatter,
  loadPersona,
  loadAssignments,
  isPersonaEnabled,
  resolvePersona,
  resolvePlayAssignment,
  resolvePersonaMode,
  mergePersona,
  PersonaMergeError,
  loadPersonaDelta,
  loadEffectivePersona,
  listEffectivePersonas,
  resolveEffectivePersona,
  PersonaDeltaLoadError,
} from './personas/index.js'

export type {
  Play,
  PlayDelta,
  PlaySources,
  PlayRequest,
  PlayRequestRejectionCode,
  PlayRequestValidationResult,
  MandatoryPlayTriggerPoint,
  DispatchPlayDeps,
  DispatchPlayInput,
  DispatchPlayResult,
  DeterministicStepInput,
  DeterministicStepResult,
  HeadlessRunInput,
} from './plays/index.js'
export {
  loadPlay,
  mergePlay,
  PlayMergeError,
  loadPlayDelta,
  loadEffectivePlay,
  listEffectivePlays,
  PlayDeltaLoadError,
  isReservedPlay,
  renderPlayManifest,
  playAvailability,
  parsePlayRequest,
  validatePlayRequest,
  MalformedPlayRequestError,
  MANDATORY_PLAY_TRIGGERS,
  resolveMandatoryPlay,
  dispatchPlay,
  runHeadlessProcess,
  type PlayAvailability,
} from './plays/index.js'
export {
  validatePlayOutput,
  founderCloseoutFromFirstContractHeading,
  parseFounderCloseoutContract,
  deriveTicketCloseDecision,
  deriveWrapupRunStatus,
  deriveWrapDisposition,
  type PlayOutputValidationInput,
  type PlayOutputValidationResult,
  type FounderCloseoutContract,
  type FounderCloseoutRunStatusVocabulary,
  type CloseoutLaunchTarget,
  type TicketCloseDecision,
} from './plays/founder-closeout.js'

export {
  composePriorityBody,
  composePriorityMarkdown,
  detectRunnerImpact,
  loadPriority,
  RUN_CRITICAL_GLOBS,
  type ComposePriorityBodyInput,
  type ComposePriorityMarkdownInput,
  type Priority,
  type RunnerImpact,
} from './priorities/index.js'
export {
  readGovernanceClaims,
  type DriftClaim,
  type DriftClaimCategory,
  type DriftClaimCategoryCount,
  type DriftClaimEvidence,
  type DriftClaimReference,
  type DriftClaimsInventory,
  type ReadGovernanceClaimsOptions,
  readRepoReality,
  type DriftRealityInventory,
  type DriftRealityPathEntry,
  type ReadRepoRealityOptions,
  compareDrift,
  type DriftComparison,
  type DriftFinding,
  type DriftFindingKind,
  type DriftFindingSeverity,
  type DriftSuggestedKind,
  buildDriftReport,
  type BuildDriftReportOptions,
  type DriftDraft,
  type DriftReportArtifact,
  type DriftReportPackage,
  applyRatifiedDriftWrites,
  type ApplyRatifiedDriftWritesInput,
  type DriftApplyResult,
  type DriftWrite,
  runDriftAudit,
  type RunDriftAuditOptions,
} from './drift/index.js'
export {
  closeTicket,
  composeTicketMarkdown,
  createTicket,
  handledOpenTicketsForPriority,
  insertOpenTicketIndexRow,
  loadTicket,
  moveTicketIndexRowToClosed,
  nextTicketId,
  readTicketIndex,
  readTickets,
  repointTicket,
  setOpenTicketIndexPriority,
  validateBinding,
  TicketBindingError,
  ticketIndexSkeleton,
  ticketTableCell,
  TICKET_OWNER,
  type TicketBindingErrorCode,
  type CloseTicketInput,
  type CloseTicketResult,
  type ComposeTicketMarkdownInput,
  type CreateTicketInput,
  type CreateTicketResult,
  type HandledTicket,
  type RepointTicketInput,
  type RepointTicketResult,
  type Ticket,
  type TicketState,
  type ValidateBindingInput,
  type ValidatedBinding,
} from './tickets/index.js'

export {
  inventoryRepo,
  type ExtensionCount,
  type LocGroup,
  type PackageInventory,
  type RepoInventory,
  type RiskHint,
  type RiskHintKind,
  type RootInventory,
  type RootValidationInventory,
  type ScriptCategory,
  type ScriptInventory,
  type WorkspaceInventory,
} from './playbooks/index.js'

export {
  scaffoldCocoderZone,
  installRoot,
  workspaceTemplateDir,
  type ScaffoldCocoderZoneOptions,
  type ScaffoldCocoderZoneResult,
} from './scaffold/index.js'

export { clamp } from './util/clamp.js'
export { mean } from './util/mean.js'
export { pluralize } from './util/pluralize.js'
export { truncate } from './util/truncate.js'

export type {
  Adapter,
  BuildInput,
  BuiltCommand,
  ModelListResult,
  PreflightCheck,
  PreflightResult,
  RunReadinessMechanism,
  RunReadinessProfile,
} from './adapter/index.js'

export { globToRegExp, matchesAny, GOVERNED_READ_DENY, OZ_ACTION_SCOPE, partitionByScope, effectiveScope, interferes, isInstructionSurface, type ScopePartition } from './write-scope/index.js'
export {
  makeGit,
  parsePorcelain,
  type Git,
  type WorktreeInfo,
  runCommitGate,
  type CommitGateInput,
  type CommitGateResult,
  AuditWriteBoundaryError,
  type AuditWriteBoundary,
  gateCommitRepair,
  type RepairCommitInput,
  type RepairCommitResult,
  COCODER_GOVERNANCE_AUTHOR,
  commitFiles,
  commitScoped,
  type CommitReceipt,
  type CommitAuthor,
  recordSuccessfulCommit,
  type SuccessfulCommitRecord,
} from './commit-gate/index.js'

export {
  runRun,
  groupLabel,
  PreflightError,
  MissingObjectiveError,
  DirtyWorkingTreeError,
  PreRunIntegrityError,
  StopRequestedError,
  type RunnerDeps,
  type CriterionResult,
  type UiBundleBuildInput,
  type RunInput,
  type RunResult,
  type PreRunGovernanceCheck,
  type PreRunIntegrityIssue,
  type RunLabelTarget,
  type RunLabelTargetType,
  type MakeJudge,
  isAwaitingFounderResolution,
  readResumeState,
  type FounderResolutionWait,
  type ResumeState,
  localRunDir,
  migrateLegacyFlatRunDirs,
  resolveLocalRunDir,
  removeLocalRunDir,
  DEFAULT_KEEP_LAST_N,
  resolveRetentionConfig,
  selectRunsToPrune,
  formatRetentionPlan,
  planRetention,
  projectionCheckerFor,
  runRetentionGc,
  rotateLogFile,
  type FlatRunDirMigrationReport,
  type LocalRunIdentity,
  type RetentionCandidate,
  type RetentionConfig,
  type RetentionPlan,
  type RetentionPlanDeps,
  type RetentionGcDeps,
  type RetentionGcResult,
  type RotateLogFileOptions,
  makeRunnerIO,
  type RunnerIO,
  type RunnerPollOptions,
  NON_LOOP_STALL_NUDGE_CAP,
  runMonitor,
  makeHeuristicJudge,
  type Judge,
  type Assessment,
  type MonitorState,
  type MonitorSample,
  type MonitorDeps,
  type MonitorOptions,
  type MonitorOutcome,
  type MonitorOutcomeReason,
  type HeuristicJudgeOptions,
  type Directive,
  parseDirective,
  type Triage,
  type Disposition,
  type TriageMode,
  parseTriage,
  type NudgeRequest,
  parseNudgeRequest,
  faultFingerprint,
  unledgeredWindowCommits,
  renderDebStatus,
  deriveTerminalProjection,
  deriveRunSummary,
  isAwaitingFounderResolutionStatus,
  isFinalizableFounderResolutionStatus,
  type RunSummary,
  captureDebTerminalSnapshot,
  renderDebTerminalSnapshotMarkdown,
  type DebStatus,
  type DebTerminalReader,
  type DebTerminalSnapshot,
  type DebTerminalSnapshotPersona,
  type RunnerPhase,
  type PlaybookStatus,
  type PlaybookGateStatus,
  type OscarState,
  type BobState,
  type VerifyState,
  renderRunRecord,
  atomSentinel,
  buildOrchestratorPrompt,
  buildObserverPrompt,
  buildBuilderStandbyPrompt,
  buildBuilderDispatch,
  buildVerifyDispatch,
  buildNextOrWrapDispatch,
  buildDebTriageDispatch,
  buildWrapupDelivery,
  commitMessage,
} from './runner/index.js'
