export {
  loadOnboardingPlaybooks,
  type OnboardingPlaybook,
  type OnboardingPlaybookMode,
  type OnboardingPlaybookPhase,
  type OnboardingPlaybookPhaseId,
  type PlaybookPhaseKind,
} from './loader.js'
export {
  loadPlaybookExecutor,
  readPlaybookExecutorState,
  resumePlaybookExecutor,
  startPlaybookExecutor,
  type FounderApproval,
  type LoadedPlaybookExecutor,
  type PlaybookExecutorDeps,
  type PlaybookExecutorResult,
  type PlaybookExecutorState,
  type PlaybookExecutorStatus,
  type PlaybookGateState,
  type PlaybookPhaseAction,
  type PlaybookPhaseActionInput,
} from './executor.js'
export {
  inventoryRepo,
  type ExtensionCount,
  type LocGroup,
  type PackageInventory,
  type RepoInventory,
  type RiskHint,
  type RiskHintKind,
  type RootInventory,
  type RootValidationInventory,
  type ScriptCategory,
  type ScriptInventory,
  type WorkspaceInventory,
} from './recon.js'
export {
  buildAgenticReconPrompt,
  runAgenticRecon,
  type AgenticReconTurn,
  type AgenticReconTurnInput,
  type ReconComplexitySignal,
  type ReconComplexitySignals,
  type ReconPassResult,
  type ReconSignalKey,
  type ReconSignalSeverity,
  type RunAgenticReconInput,
  type Subsystem,
  type SubsystemsJsonPayload,
} from './recon-pass.js'
export {
  P2_CAPS,
  P3_CAPS,
  WORKING_DAY_MINUTES,
  buildEstimate,
  summarizeEstimate,
  type BuildEstimateInput,
  type ComplexityTier,
  type DollarCostBand,
  type EstimateBand,
  type EstimateJson,
  type EstimatePricingInput,
  type ModelEstimateAssumptions,
  type P2Allocation,
  type P3Allocation,
  type PhaseCaps,
  type Projection,
  type SubsystemEstimate,
  type SubsystemSizeSignals,
} from './estimate.js'
export {
  createPlaybookPhaseAction,
  runPlaybookP1Action,
  type PlaybookP1AgentPurpose,
  type PlaybookP1AgentTurn,
  type PlaybookP1AgentTurnInput,
  type PlaybookP1Artifacts,
  type RunPlaybookP1ActionInput,
} from './p1-action.js'
export {
  createPlaybookP2PhaseAction,
  runPlaybookP2Action,
  type PlaybookFanoutResultEvent,
  type PlaybookP2Artifacts,
  type RunPlaybookP2ActionInput,
} from './p2-action.js'
export {
  createPlaybookP3PhaseAction,
  runPlaybookP3Action,
  type P3CapReason,
  type P3CapStatus,
  type P3ConvergencePayload,
  type P3FollowUpRead,
  type P3PredicateClauses,
  type P3ResolvedItem,
  type P3RoundRecord,
  type P3UnresolvedItem,
  type P3UnresolvedItemKind,
  type PlaybookCrossCheckResultEvent,
  type PlaybookP3Artifacts,
  type RunPlaybookP3ActionInput,
} from './p3-action.js'
export {
  createPlaybookP4PhaseAction,
  runPlaybookP4Action,
  type PlaybookFounderQuestionsResultEvent,
  type PlaybookP4Artifacts,
  type RunPlaybookP4ActionInput,
} from './p4-action.js'
export {
  createPlaybookP5PhaseAction,
  runPlaybookP5Action,
  type PlaybookP5Artifacts,
  type PlaybookSynthesisResultEvent,
  type RunPlaybookP5ActionInput,
} from './p5-action.js'
export {
  buildFounderQuestions,
  type P4QuestionItem,
  type P4QuestionsInput,
  type P4QuestionsPayload,
} from './p4-questions.js'
export { renderFounderQuestionsMarkdown } from './p4-render.js'
export {
  synthesizeP5Governance,
  type P5ArchitectureNote,
  type P5CandidatePriority,
  type P5DraftObjective,
  type P5FounderCheckpoint,
  type P5SynthesisInput,
  type P5SynthesisPayload,
} from './p5-synthesis.js'
export { renderP5ArchitectureNotesMarkdown, renderP5PriorityMarkdown, renderP5SynthesisMarkdown } from './p5-render.js'
export {
  buildIntentIntakePrompt,
  runIntentIntake,
  type FounderAssertedIntent,
  type FounderAssertion,
  type FounderIntentAnswers,
  type InferredPurposeClaim,
  type IntentAgentTurn,
  type IntentAgentTurnInput,
  type IntentArtifact,
  type IntentArtifactKind,
  type IntentJson,
  type IntentProvenance,
  type RunIntentIntakeInput,
} from './intent.js'
export {
  combineSourcePair,
  parseDeepReadIterationResult,
  runDeepReadSource,
  type CoverageStatus,
  type DeepReadAssignment,
  type DeepReadCapStatus,
  type DeepReadDecision,
  type DeepReadFinding,
  type DeepReadIterationResult,
  type DeepReadPredicateClauses,
  type DeepReadSource,
  type DeepReadSourceRecord,
  type DeepReadTheory,
  type DeepReadTurn,
  type DeepReadTurnInput,
  type FindingConfidence,
  type FindingSeverity,
  type P2CapReason,
  type ResidualGap,
  type RunDeepReadSourceInput,
  type SourceConvergencePayload,
  type SourcePairComparison,
  type SourcePairComparisonItem,
  type SourcePairConvergencePayload,
  type SourcePairConvergenceRecord,
} from './p2-fanout.js'
export {
  createDeepReadTurn,
  resolveDeepReadAssignments,
  type CreateDeepReadTurnInput,
  type DeepReadAssignments,
  type DeepReadDispatch,
  type ResolveDeepReadAssignmentsInput,
  type ResolveTopTier,
  type ResolveTopTierInput,
} from './p2-dispatch.js'
export {
  defaultIntentGitReader,
  enumerateIntentArtifacts,
  type EnumerateIntentArtifactsInput,
  type IntentArtifactLimits,
  type IntentCommitArtifactInput,
  type IntentGitReader,
  type IntentTagArtifactInput,
} from './intent-artifacts.js'
